"""No user-visible surface may carry a claim the code does not support.

Three consecutive review rounds on the attributed-rendering change found the
same overclaim surviving in a place the previous manual sweep had not reached:
first module docstrings, then the PR body, then the published site page. Each
round the fix was to correct that surface; each round a different one was
missed. Sweeping by hand does not converge, so the sweep lives here instead.

This is a regression net, not a semantic checker. Every pattern below is a
phrasing that actually shipped and actually had to be corrected, so a new one is
added when a new one is found rather than guessed at in advance. What it buys is
that a correction stays corrected, and that a claim reintroduced on a surface
nobody thought to look at fails a test rather than a review.

`SURFACES` is the enumeration itself, and is the part worth reviewing: a
user-visible file not matched by it is not checked at all.
"""

from __future__ import annotations

import ast
import re
import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: The sweep is repository-wide, not Python-wide. The Python tree is one
#: implementation among two, and a claim on the Rust README or in the spec is
#: read by the same person as a claim in `python/README.md`. Rooting this at
#: `python/` would enumerate zero files under `rust/`, `spec/` or
#: `conformance/` and still pass, which is the failure mode this whole file
#: exists to prevent.
REPO_ROOT = ROOT.parent

#: Every tracked path that can carry a claim a reader will believe. Generated
#: artifacts are excluded because they are renderer output, not prose.
#:
#: Deliberately wider than prose: package metadata (`pyproject.toml` description
#: and keywords, the Homebrew formula's `desc`, `action.yml`), the docs-site
#: config that supplies the site's `<meta>` description, container labels and
#: shell scripts that echo to a user have all been claim surfaces on other
#: projects even where they are currently clean here.
SURFACE_GLOBS = (
    "*.md",
    "*.html",
    "*.py",
    # Rust doc comments are a published surface: docs.rs renders them, and
    # they are what a consumer of the crate reads. Four of them in this
    # repository described a two-repository layout that no longer exists, and
    # one carried a phrasing already withdrawn from the Python tree — none of
    # which this sweep could see while it stopped at `.py`.
    "*.rs",
    "*.toml",
    "*.rb",
    "*.yml",
    "*.yaml",
    "*.mts",
    "*.sh",
    "*.json",
    "*Dockerfile",
)

#: Trees that hold recorded evidence or fixtures rather than prose. Paths are
#: repository-relative, so each names the implementation it belongs to.
EXCLUDED_PREFIXES = (
    "python/examples/artifacts/",
    "python/tests/fixtures/",
    "python/site/artifacts/",
    "python/_site/",
    # Recorded oracle output, not prose: the corpus is generated by the probes
    # and its wording is whatever the Python implementation emitted.
    "conformance/corpus/",
    # Snapshot assertions — the same argument, on the Rust side.
    "rust/crates/termproof/tests/snapshots/",
    "rust/crates/termproof-cli/tests/snapshots/",
)


def _tracked_surfaces() -> list[Path]:
    """Tracked files that can carry a user-visible claim.

    Driven off `git ls-files` rather than a hand-maintained list, so a new
    documentation page is covered the moment it is added.
    """
    listing = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    paths = []
    for name in listing.split("\0"):
        if not name or name.startswith(EXCLUDED_PREFIXES):
            continue
        path = Path(name)
        if any(path.match(glob) for glob in SURFACE_GLOBS):
            paths.append(REPO_ROOT / path)
    return paths


#: `(pattern, why, scope)`. Each is a phrasing that shipped and had to be
#: withdrawn. `scope` is a repository-relative prefix the pattern applies to,
#: or `None` for repository-wide.
#:
#: Scope exists because a withdrawn claim is withdrawn about a *particular*
#: implementation's pipeline. Most of these describe an overclaim either
#: implementation could make, so they are repository-wide; the one that names
#: the Python artifact pipeline is not true of a tree that renders no images,
#: and applying it there would flag prose that is already correctly qualified.
BANNED = (
    (
        re.compile(r"colou?r in every (?:rendered )?artifact", re.I),
        "per-step screenshots are rendered from plain text and are monochrome; "
        "name final.svg and the attributed video instead",
        None,
    ),
    (
        re.compile(r"the same attributed (?:grid|screen) the screenshots use", re.I),
        "only final.svg is rendered from the grid; say which artifact",
        None,
    ),
    (
        re.compile(r"a screenshot of the same moment are\s+(?:\n\s*)?then the same image", re.I),
        "true of the final screenshot only, not the per-step images",
        None,
    ),
    (
        re.compile(r"\basciinema\b[^.<]{0,40}\brecords the (?:session|real PTY)\b", re.I),
        "the default backend writes the cast itself; the asciinema CLI is "
        "optional, behind termproof[record]",
        None,
    ),
    (
        re.compile(r"records?[^.<]{0,40}\bwith asciinema\b", re.I),
        "same: the CLI no longer does the recording; say 'in asciinema format'",
        None,
    ),
    (
        re.compile(r"colou?r (?:SVGs|screenshots)\b", re.I),
        "unqualified plural reads as the whole artifact set; name final.svg",
        None,
    ),
    (
        # The shipped defect was an attribute list, not a sentence about dim.
        # Matching prose would flag the correctly-qualified statements that
        # replaced it ("dim is carried only when the grid is parsed from SGR
        # text"), and a pattern with false positives teaches people to add
        # exemptions rather than to read it.
        re.compile(r"bold,\s*dim,", re.I),
        "listing dim among supported attributes without naming the path; it is "
        "dropped on the cast-replay path, where final.svg and the video come from",
        # Python-only: the rationale is the Python cast-replay artifact
        # pipeline. rust/ writes no image at all today and says so in the same
        # breath as the attribute list, so the qualified statement there is
        # accurate and must not be "corrected" into a false one.
        "python/",
    ),
)


class PublicClaimsTest(unittest.TestCase):
    def test_the_enumeration_is_not_vacuous(self) -> None:
        """Guard the guard: a broken glob would silently check nothing."""
        surfaces = _tracked_surfaces()
        self.assertGreater(len(surfaces), 100, "surface enumeration collapsed")
        names = {path.relative_to(REPO_ROOT).as_posix() for path in surfaces}
        # The three surfaces that each escaped a round, plus package metadata.
        for required in (
            "python/README.md",
            "python/AGENTS.md",
            "python/site/index.html",
            "python/docs/plugins.md",
            "python/docs/plugin-protocols.md",
            "python/examples/colorstress/README.md",
            "python/termproof/cast_video.py",
            "python/termproof/attributed.py",
            "python/pyproject.toml",
            "python/action.yml",
            "python/Formula/termproof.rb",
            "python/docs-site/.vitepress/config.mts",
            "python/docker/termproof.Dockerfile",
            "python/examples/apps/multi_turn_conversation.py",
        ):
            self.assertIn(required, names, f"{required} is not being checked")

        # The surfaces the consolidation added. Rooting this guard at `python/`
        # enumerated none of them while still passing every assertion above,
        # so each tree named here is asserted separately: a prefix that stops
        # matching must fail rather than quietly shrink the sweep.
        for required in (
            "rust/docs/status-and-parity.md",
            "rust/crates/termproof/README.md",
            "rust/Cargo.toml",
            "rust/docker/termproof.Dockerfile",
            # Rust source, so a glob that stopped matching `.rs` fails here
            # rather than quietly halving the sweep.
            "rust/crates/termproof/src/schema.rs",
            "rust/crates/termproof/src/terminal/session.rs",
            "spec/001-recipe-format/spec.md",
            "conformance/README.md",
            "conformance/probe_steps.py",
        ):
            self.assertIn(required, names, f"{required} is not being checked")

        for tree in ("python/", "rust/", "spec/", "conformance/"):
            self.assertGreater(
                len([name for name in names if name.startswith(tree)]),
                0,
                f"no surface under {tree} is being checked",
            )

        # The repository root is the front door: it is the first prose a
        # stranger reads and the last place a withdrawn claim should survive.
        # Named individually because a root document is not under any tree
        # prefix asserted above, so a glob that stopped matching `*.md` at the
        # root would leave every one of them unchecked and still pass.
        for required in (
            "README.md",
            "CHANGELOG.md",
            "CONTRIBUTING.md",
            "CODE_OF_CONDUCT.md",
            "SECURITY.md",
            "SUPPORT.md",
        ):
            self.assertIn(required, names, f"{required} is not being checked")

    def test_no_surface_carries_a_withdrawn_claim(self) -> None:
        offenders = []
        for path in _tracked_surfaces():
            relative = path.relative_to(REPO_ROOT).as_posix()
            text = path.read_text(encoding="utf-8", errors="replace")
            for pattern, why, scope in BANNED:
                if scope is not None and not relative.startswith(scope):
                    continue
                for match in pattern.finditer(text):
                    line = text[: match.start()].count("\n") + 1
                    offenders.append(
                        f"{path.relative_to(REPO_ROOT).as_posix()}:{line}: "
                        f"{match.group(0)!r} — {why}"
                    )
        self.assertEqual([], sorted(offenders), "\n" + "\n".join(sorted(offenders)))

    def test_module_docstrings_are_covered_too(self) -> None:
        """Docstrings were the first surface a sweep missed.

        The file-level scan above already reads `.py` files whole, so this only
        has to prove docstrings are reachable prose rather than incidentally
        skipped.
        """
        parsed = 0
        modules = sorted((ROOT / "termproof").glob("*.py")) + sorted(
            (REPO_ROOT / "conformance").glob("*.py")
        )
        for path in modules:
            relative = path.relative_to(REPO_ROOT).as_posix()
            doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
            if doc:
                parsed += 1
                for pattern, why, scope in BANNED:
                    if scope is not None and not relative.startswith(scope):
                        continue
                    self.assertIsNone(
                        pattern.search(doc),
                        f"{relative} docstring carries a withdrawn claim — {why}",
                    )
        self.assertGreater(parsed, 5, "no module docstrings found to check")


if __name__ == "__main__":
    unittest.main()
